# Generated by Django 5.2.1 on 2025-05-24 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_backlabel_creator_frontlabel_creator_trolley_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trolley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='api.trolley')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('creator', 'trolley')},
            },
        ),
    ]
