# Generated by Django 5.2.1 on 2026-09-15 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_trolley_options'),
        ('pinned', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinned',
            name='trolley',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trollies', to='api.trolley'),
        ),
    ]
