# Generated by Django 5.2.1 on 2025-05-22 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trolley',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totes_count', models.IntegerField(choices=[(1, 'Eight Totes'), (2, 'Ten Totes')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(max_length=200)),
                ('in_use', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.IntegerField(choices=[(1, 'Square'), (2, 'Circle'), (3, 'Triangle'), (4, 'Cross'), (5, 'Squiggle'), (6, 'Heart'), (7, 'Flower'), (8, 'Penguin'), (9, 'Bowtie'), (10, 'Airplane')], default=1)),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trolley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trolley')),
            ],
        ),
        migrations.CreateModel(
            name='BackLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.IntegerField(choices=[(1, 'Square'), (2, 'Circle'), (3, 'Triangle'), (4, 'Cross'), (5, 'Squiggle'), (6, 'Heart'), (7, 'Flower'), (8, 'Penguin'), (9, 'Bowtie'), (10, 'Airplane')], default=1)),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trolley', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trolley')),
            ],
        ),
    ]
