# Generated by Django 5.2.1 on 2025-05-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trolley',
            name='notes',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
