# Generated by Django 5.2.1 on 2025-05-24 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_trolley_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backlabel',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_labels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frontlabel',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_labels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trolley',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trollies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trolley',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
