# Generated by Django 5.2.1 on 2026-09-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_backlabel_creator_frontlabel_creator_trolley_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trolley',
            options={'ordering': ['-created_at']},
        ),
    ]
